import React from 'react';

const RiskDashboard = ({ result }) => {
    if (!result) return null;

    const getRiskColor = (risk) => {
        if (risk === 'At-risk') return '#ff4d4d';
        if (risk === 'Average') return '#ffcc00';
        return '#00ff99';
    };

    const riskColor = getRiskColor(result.risk_level);

    return (
        <div className="dashboard-container" style={{ marginTop: '30px', animation: 'fadeIn 0.5s ease-out' }}>

            {/* Top Row: Summary & Percentile */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '20px' }}>

                {/* Risk Summary Card */}
                <div className="metric-card" style={{ borderLeft: `6px solid ${riskColor}` }}>
                    <p className="metric-label">Predicted Risk Level</p>
                    <h2 style={{ color: riskColor, fontSize: '2rem', margin: '10px 0' }}>{result.risk_level}</h2>
                    <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>{result.risk_description}</p>
                    <div style={{ marginTop: '15px', fontSize: '0.85rem', display: 'flex', gap: '15px' }}>
                        <div>
                            <span style={{ color: 'var(--text-muted)' }}>Confidence: </span>
                            <span style={{ fontWeight: 'bold' }}>{result.confidence}%</span>
                        </div>
                        <div>
                            <span style={{ color: 'var(--text-muted)' }}>Weighted Score: </span>
                            <span style={{ fontWeight: 'bold' }}>{result.weighted_score}</span>
                        </div>
                    </div>
                </div>

                {/* Percentile Card */}
                <div className="metric-card">
                    <p className="metric-label">Academic Percentile</p>
                    <h2 style={{ fontSize: '2.5rem', margin: '10px 0' }}>{result.percentile}th</h2>
                    <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Standing relative to 2,000 historical student profiles</p>

                    {/* Percentile Bar */}
                    <div style={{ height: '12px', background: 'rgba(255,255,255,0.1)', borderRadius: '6px', marginTop: '20px', overflow: 'hidden' }}>
                        <div style={{
                            width: `${result.percentile}%`,
                            height: '100%',
                            background: result.percentile < 50 ? '#ff4d4d' : result.percentile <= 75 ? '#ffcc00' : '#00ff99',
                            transition: 'width 1s ease-in-out'
                        }} />
                    </div>
                </div>
            </div>

            {/* Bottom Row: Insights & Recommendation */}
            <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 0.8fr', gap: '20px' }}>

                {/* Insights List */}
                <div className="metric-card">
                    <p className="metric-label" style={{ marginBottom: '15px' }}>Feature-Level Insights</p>
                    <ul style={{ listStyle: 'none', padding: 0 }}>
                        {result.feature_insights.map((insight, i) => (
                            <li key={i} style={{
                                display: 'flex',
                                alignItems: 'center',
                                marginBottom: '12px',
                                padding: '12px',
                                background: 'rgba(255,255,255,0.03)',
                                borderRadius: '8px',
                                fontSize: '0.9rem'
                            }}>
                                <span style={{ marginRight: '10px', color: riskColor }}>✦</span>
                                {insight}
                            </li>
                        ))}
                    </ul>
                </div>

                {/* Recommendation Card */}
                <div className="metric-card" style={{ background: `linear-gradient(135deg, rgba(255,255,255,0.05), ${riskColor}15)` }}>
                    <p className="metric-label">Personalized Recommendation</p>
                    <p style={{ marginTop: '15px', lineHeight: '1.6', fontSize: '1.05rem', fontWeight: '500' }}>
                        "{result.recommendation}"
                    </p>
                    <div style={{ marginTop: '20px', fontSize: '0.8rem', color: 'var(--text-muted)', fontStyle: 'italic' }}>
                        Generated by Learning Analytics Engine v2.0
                    </div>
                </div>
            </div>

        </div>
    );
};

export default RiskDashboard;